name: Push action
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: x86_64-unknown-linux-gnu
          components: rustfmt, clippy

      - if: matrix.os == 'ubuntu-latest'
        name: Prepare LD_LIBRARY_PATH (Ubuntu only)
        run: echo LD_LIBRARY_PATH=${pythonLocation}/lib >> $GITHUB_ENV

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy -- -Dwarnings
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test --verbose
